[project]
name = "dcpiano"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "armtrace",
    "mediapipe>=0.10.14",
    "numpy>=2.5.1",
    "opencv-python>=5.0.0.93",
    "pyyaml>=6.0.3",
    "tqdm>=4.70.0",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]

[project.scripts]
dcpiano = "dcpiano.cli:main"

[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[tool.uv.sources]
armtrace = { git = "https://github.com/sivakovivan/armtrace" }
